# Theoretical Considerations

@claerboutElectronicDocumentsGive1992 define reproducibility as the ability to obtain the same results, from the same dataset.
Conversely, they call a result replicable if one draws the same conclusion from a new dataset.
This thesis concerns itself with the former, providing researchers with an accessible analysis workflow, that is virtually guaranteed to reproduce across time and devices.

The scientific community agrees that ideally their work should be reproducible.
Indeed it may be hard to find a researcher who distrusts a result because it is reproducible; to the contrary, many argue it is "good scientific practice" to ensure what they consider reproducible [@AnnouncementReducingOur2013; @dfg2019; @epskamp2019rep].
Several reasons, practical and meta-scientific, justify this consensus of reproducibility as a minimal standard of Science.

Reproducibility makes researchers life more productive in two ways:
The act of reproduction provides, at the most basic level, an opportunity for the researcher to spot errors. At the same time, other researchers may also benefit from reusing materials from an analysis they reproduced.

Beyond these two purely pragmatic reasons, reproduction is crucial, depending on the philosophical view of Science one subscribes to, because it allows independent validation and enables replication.
Philosophers of Science characterise Science mainly as a shared method of determining whether or not a statement about the world is "true" [@andersonScientificMethod2016] or more broadly evaluating the statements verisimilitude [@popperCommentsTruthGrowth1962; @tichyVerisimilitudeRedefined1976; @gilbertModelBuildingDefinition1991; @meehlAppraisingAmendingTheories1990].
If this method is for experts to agree on the assumptions and deduce "truth", reproducibility is hardly necessary.
On the other hand, it does gain importance if one induces facts by carefully observing the world.
The decisive difference between the above approaches is that the former gains credibility by the authority of the experts, while the latter is trustworthy because anyone may verify it.

Accepting induction as a scientific method hence hinges on the verifiability by others.
Some have even argued that such democratisation of Science is what fueled the so-called scientific revolution [@heilbronOxfordCompanionHistory2004, Scientific Revolution].
The scientific revolution had the experiment as an agreed-upon method to observe reality, and a much later revolution provides statistical modelling [@rodgersEpistemologyMathematicalStatistical2010] as a means to induction.
This consensus about how to observe and how to induce gives modern scientific enterprises much of their credibility.
Two reasons justify why we must assume reproducibility as a scientific standard if we accept induction as a scientific method:
First, it enables independent verification of the process of induction, and second, it dramatically simplifies replication as a means to verify the induced truths.

However, neither the practical reasons that results might be less error-prone and more reusable nor that the process of induction and the induced facts are more straightforward to verify, if reproducible, derive strictly from the definition of reproducibility provided by @claerboutElectronicDocumentsGive1992 given above.
A simple thought experiment illustrates this shortcoming:
Imagine a binary---therefore only machine readable---program being perfectly reproducible; hence upon the input of the same dataset, it fills a scientific manuscript with the same numbers at the right places.
Furthermore, let us assume this hypothetical program may never hold if the dataset changes.
Does the predicate "reproducible" in this situation reduce the number of mistakes or enables reuse? Unlikely.
Or could one audit it and use it in replication? Hardly.
This admittedly constructed case of a reproducible black box shows that we are not interested in reproducibility but rather in its side effects.
Because it is a binary program, it does not enhance understanding and because it is not applicable to other datasets, it does not facilitate productivity.
In fact such a program does not grant the researcher any practical or metascientific advantages over non-reproducible research products.

Spoiling its elegant simplicity, I therefore extend the definition by @claerboutElectronicDocumentsGive1992 to address this issue, by further demanding that reproducibility must allow criticism and facilitate replication:

> A reproducible scientific product allows one to obtain the same results from the same dataset in a way that enables substantive criticism and therefore facilitates replication.

Thus, transparency should enable reproducibility: Ensuring a clear link between the data and its results, promotes both replicability and reproducibility.
Comprehension is a necessary precondition to form substantive criticism, which motivates the iterative scientific process.
Bowing to this general notion, scientific publications are required to provide enough detail about the research process so that others may contribute constructive criticism.
I am convinced that we should accept the same standard for everything that is published --- including code.

Consequently, something is no longer either reproducible or not, but there are shades because a research product can promote replication and comprehension to varying degrees.
Also note that a scientific result can facilitate replication without anyone ever attempting to replicate it, e.g. by educating other researchers about the analyses method, being openly accessible and providing reusable components.

Hence, reproducibility has a technical side, which is ensuring the same results, and a non-technical side, which is facilitating understanding.
The former relates to the practical advantages while the latter serves the metascientific purposes of reproducibility.
An important caveat of the technical aspect is that generating the same results from the same data should always be possible regardless of time and machine.
As such, a reproducible analysis should be:

1. understandable by other researchers,
2. transferable across machines,
3. conserved through time.

This much more demanding standard of reproducibility is justified by two recent developments in the social sciences in general and psychology in particular: the emergence of a "replication crises" [@ioannidisWhyMostPublished2005] and the rise of "machine learning" [@jordanMachineLearningTrends2015] as a scientific tool.
Both trends link to the use of statistical modeling on which the social sciences became reliant for testing and developing their theories [@gigerenzerNullRitualWhat2004; @meehlTheoreticalRisksTabular1978].
It turns out that, if one fits the very same statistical model as published on newly gathered data, one fails more often to achieve the same results as published then one succeeds. [@opensciencecollaborationEstimatingReproducibilityPsychological2015].

Such failure to replicate findings that were believed to be robust has grown to a level that some social scientists call a crisis.
They put forth various causes and remedies to this crisis.
Most remedies share a common motif: transparency.
Some call for Bayesian statistics [@maxwellPsychologySufferingReplication2015], as it makes assumptions more explicit, or demand preregistration [@nosekPreregistrationRevolution2018] as a means to clarify how to analyse the data, beforehand and publicly. Others require the researchers to publish their data [@boultonScienceOpenEnterprise2012].
Similar calls for transparency, as a response to the replication crises, have formed the open science movement which stresses the necessity of six principles [@krakerCaseOpenScience2011]:

* Open Access,
* Open Data,
* Open Source,
* Open Methodology,
* Open Peer Review and
* Open Educational Resources.

I argue that a research product resting on these pillars facilitates replication optimally and hence, it satisfies the highest standard of reproducibility.
If everyone has access to a scientific product and its data along with the source code, everyone has the possibility of understanding the underlying methodology, which enables them to criticise the results and educate themselves.
Having done so, they are in the best position for replication.
Hence, any one's ability to reproduce such a result gives a tangible affirmation of its usefulness to the scientific community.

While reproducibility is no hurdle if one can perform the calculations needed with a pocket calculator, the more and more frequent use of computer-intensive methods renders such expectation questionable.
The use of machine learning techniques, which has been once enabled by the computer taking over strenuous works, now impedes our quest for reproducibility. 
More massive amounts of more complicated computer code than ever before create room for errors and misunderstandings, leading the machine learning community to believe that they face a reproducibility crisis themselves [@hutsonArtificialIntelligenceFaces2018].
Yet, I am far from calling for abstinence from machine learning, just because it complicates reproduction, but want to emphasise the need for solutions that allow anyone to reproduce even the most sophisticated analysis.

@peikertReproducibleDataAnalysis2019 put forth an analysis workflow which provides this accessibility for everyone to reproduce any kind of analysis.
However, they fail to provide the same level of convenience for the researcher who created an analysis in the first place.
Setting up the workflow eats up a considerable amount of the researcher's time, which they may rather spend on advancing research.
This additional effort offsets the increase in productivity, promised by reproducibility, which I regard as most significant in the workflows adoption.
Persuading researchers, who find the meta-scientific argumentation noble but impractical, do not care about it or even oppose it, requires concrete, practical benefits.
Luckily, most of this setup process may become automated, letting the researcher enjoy the workflows advantages while decreasing the efforts necessary to achieve them.
Providing a version of the analysis workflow by @peikertReproducibleDataAnalysis2019 that is easier to use and more accessible is the goal of this thesis and the herein presented `repro`-package for the R programming language [@R-repro].
